# Generated by Django 5.0 on 2024-12-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('tax_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Tax ID')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('representative', models.CharField(blank=True, max_length=255, verbose_name='Main Representative')),
                ('services', models.ManyToManyField(blank=True, related_name='companies', to='Company.service', verbose_name='Contracted Services')),
            ],
            options={
                'verbose_name': 'Client Company',
                'verbose_name_plural': 'Client Companies',
            },
        ),
    ]
