# Generated by Django 5.0 on 2024-12-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/company/'),
        ),
    ]
