# Generated by Django 5.0 on 2024-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, verbose_name='Genero'),
        ),
    ]
