# Generated by Django 5.0 on 2024-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_employee_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='0000', max_length=100),
        ),
    ]
