# Generated by Django 5.1.4 on 2024-12-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_order_status_alter_order_date_alter_order_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='Company.menu'),
        ),
    ]
