# Generated by Django 5.1.4 on 2024-12-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Company.company', verbose_name='Empresa')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='Company.menu', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Menú de Empresa',
                'verbose_name_plural': 'Menús de Empresas',
            },
        ),
    ]
