# Generated by Django 5.1.4 on 2024-12-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_alter_menu_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus_company', to='Company.company', verbose_name='Empresas'),
        ),
    ]
