# Generated by Django 5.1.4 on 2024-12-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_menu_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_selections', to='Company.employee')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.menu')),
            ],
        ),
    ]
