# Generated by Django 5.1.4 on 2024-12-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_menuselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuselection',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='menuselection',
            name='menu_item',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_company', to='Company.company'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=20, verbose_name='Horario'),
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plato')),
                ('description', models.TextField(verbose_name='Descripción del Plato')),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_menu', to='Company.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyMenu',
        ),
        migrations.DeleteModel(
            name='MenuSelection',
        ),
    ]
