# Generated by Django 5.1.4 on 2024-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
    ]
