# Generated by Django 5.1.4 on 2024-12-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_alter_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoría del Plato')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Categoría')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/category/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, verbose_name='Día')),
                ('time', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=20, verbose_name='Horario')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),

        migrations.AddField(
            model_name='plato',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/plato/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio del Plato'),
        ),
        migrations.AddField(
            model_name='plato',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_category', to='Company.category'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=50, verbose_name='Tipo de Servicio')),
                ('delivery_schedule', models.TimeField(blank=True, null=True, verbose_name='Horario de Entrega')),
                ('payment_terms', models.TextField(verbose_name='Términos de Pago')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='Company.company', verbose_name='Cliente')),
            ],
        ),
    ]
