# Generated by Django 5.1.4 on 2024-12-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_category_globalmenu_menu_img_plato_img_plato_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='img',
        ),
    ]
