# Generated by Django 5.1.4 on 2024-12-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/plato/'),
        ),
    ]
