# Generated by Django 5.1.4 on 2024-12-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_plato_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_menu', to='Company.menu'),
        ),
    ]
