# Generated by Django 5.1.4 on 2024-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0032_alter_employee_password_alter_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cargo_representante',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo del Representante'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_representante',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contacto del Representante'),
        ),
    ]
