# Generated by Django 5.1.4 on 2024-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0033_company_cargo_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='DNI'),
        ),
    ]
