# Generated by Django 5.1.4 on 2024-12-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0034_company_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Número de Contrato'),
        ),
    ]
