# Generated by Django 5.1.4 on 2024-12-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0035_contract_number_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='service_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='service_type',
            field=models.ManyToManyField(to='Company.service', verbose_name='Tipo de Servicio'),
        ),
    ]
