# Generated by Django 5.1.4 on 2024-12-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_alter_contract_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='media/plato/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/plato/'),
        ),
    ]
