# Generated by Django 5.1.4 on 2024-12-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0040_menuchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos_menu', to='Company.category'),
        ),
    ]
