# Generated by Django 5.1.4 on 2024-12-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0042_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codigo de acceso'),
        ),
    ]
