# Generated by Django 5.1.4 on 2024-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0044_company_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuchoices',
            name='role',
            field=models.CharField(blank=True, choices=[('ejecutivo', 'Ejecutivo'), ('estandar', 'Estandar')], default='estandar', max_length=10, verbose_name='Role'),
        ),
    ]
