# Generated by Django 5.1.4 on 2024-12-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0048_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_company', to='Company.restaurant'),
        ),
    ]
