# Generated by Django 5.1.4 on 2024-12-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0049_company_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('ejecutivo', 'Ejecutivo'), ('estandar', 'Estandar'), ('representante', 'Representante')], max_length=15, verbose_name='Role'),
        ),
    ]
