# Generated by Django 5.1.4 on 2025-01-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0050_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/order/'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Plato'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio del Plato'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Company.employee'),
        ),
    ]
