# Generated by Django 5.1.4 on 2025-01-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0051_order_img_order_name_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID'),
        ),
    ]
