# Generated by Django 5.1.4 on 2025-01-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0052_restaurant_tax_id_alter_company_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='firma_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma de la Empresa'),
        ),
        migrations.AddField(
            model_name='contract',
            name='firma_resturant',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma del Restaurante'),
        ),
    ]
