# Generated by Django 5.1.4 on 2025-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0055_movements_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Movimiento'),
        ),
    ]
