# Generated by Django 5.1.4 on 2025-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0056_movements_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En preparacion'), ('listo', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
