# Generated by Django 5.1.4 on 2025-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0059_alter_order_options_rename_menu_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En preparacion'), ('enviado', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
