# Generated by Django 5.1.4 on 2025-01-31 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0061_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='Company.company', verbose_name='Contrato de compañia'),
        ),
    ]
