# Generated by Django 5.1.4 on 2025-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0062_alter_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='companies', to='Company.service', verbose_name='Servicios contratados'),
        ),
    ]
