# Generated by Django 5.1.4 on 2025-01-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0063_alter_company_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compañia', 'verbose_name_plural': 'Compañias'},
        ),
    ]
