# Generated by Django 5.1.4 on 2025-02-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0065_invoice_is_facturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'En preparacion'), ('enviado', 'En camino'), ('facturado', 'Facturado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
