# Generated by Django 5.1.4 on 2025-02-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0066_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_paid',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total pagado'),
        ),
        migrations.AddField(
            model_name='company',
            name='total_to_pay',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total a pagar'),
        ),
    ]
