# Generated by Django 5.1.4 on 2025-02-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0067_company_total_paid_company_total_to_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='total_paid',
            new_name='total_pay',
        ),
    ]
