# Generated by Django 5.1.4 on 2025-02-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0068_rename_total_paid_company_total_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
