# Generated by Django 5.1.4 on 2025-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0069_remove_invoice_due_date_alter_invoice_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/employee/'),
        ),
    ]
