# Generated by Django 5.1.4 on 2024-12-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='ConfigurationApp',
        ),
    ]
